Hw3
Demon1056/nodejs-rest-api pull request #2
Opened 2023-01-25 14:38 UTC by Demon1056

2023-01-25 17:05 UTC, KhYulian requested changes
Потрібні правки

2023-01-25 17:05 UTC, KhYulian commented on controlles/controllers.js
> +    if (!req.body.name & !req.body.email & !req.body.phone & !req.body.favorite) { return res.status(400).json({ "message": "missing fields" }) }
Для валідації використовуйте окрему middleware, яка спрацьвуватиме перед контроллером та валідуватиме body

2023-01-25 17:05 UTC, KhYulian commented on controlles/controllers.js
> +    if (!req.body) { return res.status(400).json({ "message": "missing field favorite" }) }
Аналогічно

2023-01-25 17:05 UTC, KhYulian commented on models/contactServer.js
> +const { Schema, model } = require('mongoose');
Робіть пусту строку після останнього імпорту

2023-01-25 17:06 UTC, KhYulian commented on controlles/controllers.js
>      }
І цю валідацію також винесіть в middleware

2023-01-26 14:09 UTC, Demon1056 commented
Здається виправив. Проте незнаю чи правильно виводжу повідомлення про помилку та чи потрібно було писати 3 мідлвера для валідації чи можна було обійтися одним?

2023-01-26 14:39 UTC, KhYulian commented
> Здається виправив. Проте незнаю чи правильно виводжу повідомлення про помилку та чи потрібно було писати 3 мідлвера для валідації чи можна було обійтися одним?

Middlewar може бути один універсальний. А може буде дікілька, специфічних для кожного маршруту. В даному випадку один доречніший, бо багато повторення, але це не критично 

Помилки неправильно обробляєте. Загалом в next потрібно передавати об'єкт помилки next(error) та цю помилку потім обробити у error handling middleware (витягнути message, statusCode та відправити відповідний респонс) - та що йде останньою в app.js

2023-01-26 14:41 UTC, KhYulian requested changes
Потрібні правки

2023-01-26 14:41 UTC, KhYulian commented on middleware/contacts_middleware.js
> +            return next(res.status(400).json(`"message": "missing fields"`))
В цій перевірці немає потреби, адже Joi перевіряє усі поля на відповідність схемі

2023-01-26 14:41 UTC, KhYulian commented on middleware/contacts_middleware.js
> +            return next(res.status(400).json(`"message": "missing field favorite"`))
створіть схему Joi для оновлення поля favorite у контакту, по аналогії з іншими схемами.

2023-01-29 12:01 UTC, KhYulian approved these changes
-

2023-02-01 14:28 UTC, Demon1056 commented
Доробив код з обробкою помилок

2023-02-01 15:56 UTC, KhYulian approved these changes
Чудова робота!

2023-02-01 15:57 UTC, merged